### ISSUE TITLE
BE - US2 Consume API to find a selection of songs

### ISSUE THREAD

**Issue by kameronk92** [FasTracks/FasTracks-BE#2]
this will use `request.body` the endpoint `POST api/v1/playlists`

As the BE App, 
When I receive a POST (JSON) of the playlist params
I consume the Spotify /recommendations API to generate a selection of songs based on passed params

- genre
- BPM
- workout duration

and will make a request from `https://api.spotify.com/v1/recommendations`

**Comment by trpubz** [comment]
16 songs
